# Generated by Django 3.1.5 on 2021-01-19 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseinstructors',
            name='Facebook',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='courseinstructors',
            name='instagram',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='courseinstructors',
            name='twitter',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
