# Generated by Django 3.1.5 on 2021-01-20 07:02

import backend.users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('Full_name', models.CharField(blank=True, max_length=150, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=150, null=True)),
                ('location', models.CharField(blank=True, max_length=50, null=True)),
                ('user_type', models.CharField(choices=[('A', 'A'), ('U', 'U'), ('I', 'I')], max_length=1)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='')),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_stuff', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', backend.users.models.UserManager()),
            ],
        ),
    ]
