# Generated by Django 3.1.5 on 2021-01-20 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product_category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category', models.CharField(max_length=150)),
                ('Category_Description', models.TextField(blank=True, null=True)),
                ('Image', models.ImageField(blank=True, null=True, upload_to='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProductName', models.CharField(max_length=150)),
                ('NumberInStock', models.IntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ProductDescription', models.TextField(blank=True, null=True)),
                ('MainImage', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('Image1', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('Image2', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('Image3', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('Image4', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ProductCategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.product_category')),
            ],
        ),
    ]
